--CREATE USER C##LUMOS IDENTIFIED BY LUMOS;

--GRANT CONNECT, RESOURCE TO C##LUMOS;

--ALTER USER C##LUMOS DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS; 
--ALTER USER C##LUMOS QUOTA 1024M ON SYSTEM;

DROP TABLE PRODUCT_IMAGE;

CREATE TABLE PRODUCT_IMAGE
(
    PD_IMG_PATH    VARCHAR2(255),
    PD_CODE    NUMBER NOT NULL
);

ALTER TABLE PRODUCT_IMAGE
DROP PRIMARY KEY;

COMMENT ON COLUMN PRODUCT_IMAGE.PD_IMG_PATH IS '이미지경로';

COMMENT ON COLUMN PRODUCT_IMAGE.PD_CODE IS '상품코드';


DROP TABLE QUESTION;

CREATE TABLE QUESTION
(
    QUESTION_CODE    NUMBER NOT NULL,
    QUESTION_TITLE    VARCHAR2(50) NOT NULL,
    QUESTION_CATEGORY    VARCHAR2(50) NOT NULL,
    QUESTION_CONTENT    VARCHAR2(1000) NOT NULL,
    ANSWER_CONTENT    VARCHAR2(1000),
    QUESTION_STATUS    VARCHAR2(20) DEFAULT '미해결' NOT NULL ,
    MEMBER_CODE    NUMBER NOT NULL
);

ALTER TABLE QUESTION
DROP PRIMARY KEY;

ALTER TABLE QUESTION
 ADD CONSTRAINT QUESTION_PK PRIMARY KEY ( QUESTION_CODE );
 
DROP SEQUENCE SEQ_QUESTION_CODE;
CREATE SEQUENCE SEQ_QUESTION_CODE
START WITH 1
NOCACHE;


COMMENT ON COLUMN QUESTION.QUESTION_CODE IS '문의번호';

COMMENT ON COLUMN QUESTION.QUESTION_TITLE IS '문의제목';

COMMENT ON COLUMN QUESTION.QUESTION_CATEGORY IS '문의유형';

COMMENT ON COLUMN QUESTION.QUESTION_CONTENT IS '문의내용';

COMMENT ON COLUMN QUESTION.ANSWER_CONTENT IS '답변내용';

COMMENT ON COLUMN QUESTION.QUESTION_STATUS IS '해결상태';

COMMENT ON COLUMN QUESTION.MEMBER_CODE IS '회원코드';


DROP TABLE QUESTION_IMG;

CREATE TABLE QUESTION_IMG
(
    QUESTION_IMG_CODE    NUMBER NOT NULL,
    ORGINAL_NAME    VARCHAR2(255),
    NEW_NAME    VARCHAR2(255),
    QUESTION_CODE    NUMBER NOT NULL
);

ALTER TABLE QUESTION_IMG
DROP PRIMARY KEY;

ALTER TABLE QUESTION_IMG
 ADD CONSTRAINT QUESTION_IMG_PK PRIMARY KEY ( QUESTION_IMG_CODE );
 
DROP SEQUENCE SEQ_QUESTION_IMG_CODE;
CREATE SEQUENCE SEQ_QUESTION_IMG_CODE
START WITH 1
NOCACHE;

COMMENT ON COLUMN QUESTION_IMG.QUESTION_IMG_CODE IS '문의사진코드';

COMMENT ON COLUMN QUESTION_IMG.ORGINAL_NAME IS '원본사진명';

COMMENT ON COLUMN QUESTION_IMG.NEW_NAME IS '리네임사진명';

COMMENT ON COLUMN QUESTION_IMG.QUESTION_CODE IS '문의번호';


DROP TABLE REVIEW_IMAGE;

CREATE TABLE REVIEW_IMAGE
(
    IMAGE_CODE    NUMBER NOT NULL,
    ORIGIN_NM    VARCHAR2(255),
    NEW_NM    VARCHAR2(255),
    REVIEW_CODE    NUMBER NOT NULL
);

ALTER TABLE REVIEW_IMAGE
DROP PRIMARY KEY;

ALTER TABLE REVIEW_IMAGE
 ADD CONSTRAINT REVIEW_IMAGE_PK PRIMARY KEY ( IMAGE_CODE );
 
DROP SEQUENCE SEQ_IMAGE_CODE;
CREATE SEQUENCE SEQ_IMAGE_CODE
START WITH 1
NOCACHE;

COMMENT ON COLUMN REVIEW_IMAGE.IMAGE_CODE IS '사진코드';

COMMENT ON COLUMN REVIEW_IMAGE.ORIGIN_NM IS '사진명';

COMMENT ON COLUMN REVIEW_IMAGE.NEW_NM IS '저장된사진명';

COMMENT ON COLUMN REVIEW_IMAGE.REVIEW_CODE IS '리뷰코드';


DROP TABLE TBL_AUTHORITY;

CREATE TABLE TBL_AUTHORITY
(
    AUTHORITY_CODE    NUMBER NOT NULL,
    AUTHORITY_NAME    VARCHAR2(255) NOT NULL,
    AUTHORITY_DESC    VARCHAR2(1000) NOT NULL
);

ALTER TABLE TBL_AUTHORITY
DROP PRIMARY KEY;

ALTER TABLE TBL_AUTHORITY
 ADD CONSTRAINT TBL_AUTHORITY_PK PRIMARY KEY ( AUTHORITY_CODE );

COMMENT ON COLUMN TBL_AUTHORITY.AUTHORITY_CODE IS '권한코드';

COMMENT ON COLUMN TBL_AUTHORITY.AUTHORITY_NAME IS '권한명';

COMMENT ON COLUMN TBL_AUTHORITY.AUTHORITY_DESC IS '권한설명';


DROP TABLE TBL_COMPANY;

CREATE TABLE TBL_COMPANY
(
    BSR_NUM    NUMBER NOT NULL,
    CP_NM    VARCHAR2(100) NOT NULL,
    RP_NM    VARCHAR2(100) NOT NULL,
    CP_TEL    VARCHAR2(100) NOT NULL,
    BS_TYPE    VARCHAR2(100) NOT NULL,
    BS_ITEM    VARCHAR2(100) NOT NULL,
    CP_ADS_NUM    VARCHAR2(100) NOT NULL,
    CP_ADS    VARCHAR2(100) NOT NULL,
    CP_ADS_DETAIL    VARCHAR2(100) NOT NULL,
    CP_EMAIL    VARCHAR2(100) NOT NULL
);

ALTER TABLE TBL_COMPANY
DROP PRIMARY KEY;

ALTER TABLE TBL_COMPANY
 ADD CONSTRAINT TBL_COMPANY_PK PRIMARY KEY ( BSR_NUM );

COMMENT ON COLUMN TBL_COMPANY.BSR_NUM IS '사업자 등록 번호';

COMMENT ON COLUMN TBL_COMPANY.CP_NM IS '상호';

COMMENT ON COLUMN TBL_COMPANY.RP_NM IS '대표자 성명';

COMMENT ON COLUMN TBL_COMPANY.CP_TEL IS '대표 전화';

COMMENT ON COLUMN TBL_COMPANY.BS_TYPE IS '업태';

COMMENT ON COLUMN TBL_COMPANY.BS_ITEM IS '종목';

COMMENT ON COLUMN TBL_COMPANY.CP_ADS_NUM IS '사업장 우편번호';

COMMENT ON COLUMN TBL_COMPANY.CP_ADS IS '사업장 주소';

COMMENT ON COLUMN TBL_COMPANY.CP_ADS_DETAIL IS '사업장 상세 주소';

COMMENT ON COLUMN TBL_COMPANY.CP_EMAIL IS '이메일';


DROP TABLE TBL_MEMBER;

CREATE TABLE TBL_MEMBER
(
    MEMBER_CODE    NUMBER NOT NULL,
    MEMBER_ID    VARCHAR2(255) NOT NULL,
    MEMBER_PASSWORD    VARCHAR2(255) NOT NULL,
    MEMBER_NAME    VARCHAR2(255) NOT NULL,
    MEMBER_BIRTH    VARCHAR2(50) NOT NULL,
    MEMBER_GEN    CHAR(3) NOT NULL,
    MEMBER_PHONE    VARCHAR2(14) NOT NULL,
    MEMBER_EMAIL    VARCHAR2(50) NOT NULL,
    MEMBER_ADS_NUM    VARCHAR2(100) NOT NULL,
    MEMBER_ADS    VARCHAR2(100) NOT NULL,
    MEMBER_ADS_DETAIL    VARCHAR2(100) NOT NULL
);

ALTER TABLE TBL_MEMBER
DROP PRIMARY KEY;

ALTER TABLE TBL_MEMBER
 ADD CONSTRAINT TBL_MEMBER_PK PRIMARY KEY ( MEMBER_CODE );

DROP SEQUENCE SEQ_MEMBER_CODE;
CREATE SEQUENCE SEQ_MEMBER_CODE
START WITH 1
NOCACHE;

COMMENT ON COLUMN TBL_MEMBER.MEMBER_CODE IS '회원코드';

COMMENT ON COLUMN TBL_MEMBER.MEMBER_ID IS '아이디';

COMMENT ON COLUMN TBL_MEMBER.MEMBER_PASSWORD IS '비밀번호';

COMMENT ON COLUMN TBL_MEMBER.MEMBER_NAME IS '이름';

COMMENT ON COLUMN TBL_MEMBER.MEMBER_BIRTH IS '생년월일';

COMMENT ON COLUMN TBL_MEMBER.MEMBER_GEN IS '성별';

COMMENT ON COLUMN TBL_MEMBER.MEMBER_PHONE IS '휴대전화';

COMMENT ON COLUMN TBL_MEMBER.MEMBER_EMAIL IS '이메일';

COMMENT ON COLUMN TBL_MEMBER.MEMBER_ADS_NUM IS '우편번호';

COMMENT ON COLUMN TBL_MEMBER.MEMBER_ADS IS '주소';

COMMENT ON COLUMN TBL_MEMBER.MEMBER_ADS_DETAIL IS '상세주소';


DROP TABLE TBL_MEMBER_ROLE;

CREATE TABLE TBL_MEMBER_ROLE
(
    MEMBER_CODE    NUMBER NOT NULL,
    AUTHORITY_CODE    NUMBER NOT NULL
);

ALTER TABLE TBL_MEMBER_ROLE
DROP PRIMARY KEY;

COMMENT ON COLUMN TBL_MEMBER_ROLE.MEMBER_CODE IS '회원코드';

COMMENT ON COLUMN TBL_MEMBER_ROLE.AUTHORITY_CODE IS '권한코드';

DROP SEQUENCE SEQ_AUTHORITY_CODE;
CREATE SEQUENCE SEQ_AUTHORITY_CODE
START WITH 1
NOCACHE;

DROP TABLE TBL_ORDER;

CREATE TABLE TBL_ORDER
(
    ORDER_NUM    NUMBER NOT NULL,
    ORDER_CODE    VARCHAR2(50),
    ORDER_DATE    DATE,
    PAYMENT_MT    VARCHAR2(50),
    ORDER_PC    NUMBER,
    DELIVERY_PC    NUMBER,
    TOTAL_PC    NUMBER NOT NULL,
    DELIVERY_MT    VARCHAR2(50),
    DELIVERY_CP    VARCHAR2(50),
    DELIVERY_NUM    VARCHAR2(50),
    ST_ORDER    VARCHAR2(50) DEFAULT 'N' NOT NULL,
    ST_CLAIM    VARCHAR2(50),
    ST_PAYMENT    VARCHAR2(50),
    CG_NM    VARCHAR2(50),
    CG_PH    VARCHAR2(50),
    CG_ADS_NUM    VARCHAR2(50),
    CG_ADS    VARCHAR2(255),
    CG_ADS_DETAIL    VARCHAR2(255),
    MEMBER_CODE    NUMBER NOT NULL
);

ALTER TABLE TBL_ORDER
DROP PRIMARY KEY;

ALTER TABLE TBL_ORDER
 ADD CONSTRAINT TBL_ORDER_PK PRIMARY KEY ( MEMBER_CODE,ORDER_NUM );
 
DROP SEQUENCE SEQ_ORDER_NUM;
CREATE SEQUENCE SEQ_ORDER_NUM
START WITH 1
NOCACHE;

COMMENT ON COLUMN TBL_ORDER.ORDER_NUM IS '주문식별번호';

COMMENT ON COLUMN TBL_ORDER.ORDER_CODE IS '주문코드';

COMMENT ON COLUMN TBL_ORDER.ORDER_DATE IS '주문일';

COMMENT ON COLUMN TBL_ORDER.PAYMENT_MT IS '결제 방법';

COMMENT ON COLUMN TBL_ORDER.ORDER_PC IS '주문 금액';

COMMENT ON COLUMN TBL_ORDER.DELIVERY_PC IS '배송비';

COMMENT ON COLUMN TBL_ORDER.TOTAL_PC IS '합계 금액';

COMMENT ON COLUMN TBL_ORDER.DELIVERY_MT IS '배송 방법';

COMMENT ON COLUMN TBL_ORDER.DELIVERY_CP IS '택배사';

COMMENT ON COLUMN TBL_ORDER.DELIVERY_NUM IS '송장번호';

COMMENT ON COLUMN TBL_ORDER.ST_ORDER IS '주문상태';

COMMENT ON COLUMN TBL_ORDER.ST_CLAIM IS '클레임상태';

COMMENT ON COLUMN TBL_ORDER.ST_PAYMENT IS '결제상태';

COMMENT ON COLUMN TBL_ORDER.CG_NM IS '수하인 이름';

COMMENT ON COLUMN TBL_ORDER.CG_PH IS '수하인 연락처';

COMMENT ON COLUMN TBL_ORDER.CG_ADS_NUM IS '배송지 우편번호';

COMMENT ON COLUMN TBL_ORDER.CG_ADS IS '배송지 주소';

COMMENT ON COLUMN TBL_ORDER.CG_ADS_DETAIL IS '배송지 주소 상세';

COMMENT ON COLUMN TBL_ORDER.MEMBER_CODE IS '회원코드';


DROP TABLE TBL_ORDER_PRODUCT;

CREATE TABLE TBL_ORDER_PRODUCT
(
    ORDER_PD_NUM    NUMBER NOT NULL,
    ORDER_AMOUNT    NUMBER NOT NULL,
    ORDER_NUM    NUMBER NOT NULL,
    PD_CODE    NUMBER NOT NULL
);

ALTER TABLE TBL_ORDER_PRODUCT
DROP PRIMARY KEY;

ALTER TABLE TBL_ORDER_PRODUCT
 ADD CONSTRAINT TBL_ORDER_PRODUCT_PK PRIMARY KEY ( ORDER_PD_NUM );
 
DROP SEQUENCE SEQ_ORDER_PD_NUM;
CREATE SEQUENCE SEQ_ORDER_PD_NUM
START WITH 1
NOCACHE;

COMMENT ON COLUMN TBL_ORDER_PRODUCT.ORDER_PD_NUM IS '주문제품정보 식별번호';

COMMENT ON COLUMN TBL_ORDER_PRODUCT.ORDER_AMOUNT IS '구매수량';

COMMENT ON COLUMN TBL_ORDER_PRODUCT.ORDER_NUM IS '주문식별번호';

COMMENT ON COLUMN TBL_ORDER_PRODUCT.PD_CODE IS '상품코드';


DROP TABLE TBL_PRODUCT;

CREATE TABLE TBL_PRODUCT
(
    PD_CODE    NUMBER NOT NULL,
    PD_NAME    VARCHAR2(255) NOT NULL,
    PD_PRICE    NUMBER NOT NULL,
    PD_DESC    VARCHAR2(255),
    PD_OP    VARCHAR2(40) NOT NULL,
    PD_STOCK    NUMBER NOT NULL,
    CAT_MAIN    VARCHAR2(50) NOT NULL,
    CAT_SUB    VARCHAR2(50) NOT NULL
);

ALTER TABLE TBL_PRODUCT
DROP PRIMARY KEY;

ALTER TABLE TBL_PRODUCT
 ADD CONSTRAINT TBL_PRODUCT_PK PRIMARY KEY ( PD_CODE );
 
DROP SEQUENCE SEQ_PD_CODE;
CREATE SEQUENCE SEQ_PD_CODE
START WITH 1
NOCACHE;

COMMENT ON COLUMN TBL_PRODUCT.PD_CODE IS '상품코드';

COMMENT ON COLUMN TBL_PRODUCT.PD_NAME IS '상품명';

COMMENT ON COLUMN TBL_PRODUCT.PD_PRICE IS '상품가격';

COMMENT ON COLUMN TBL_PRODUCT.PD_DESC IS '상품설명';

COMMENT ON COLUMN TBL_PRODUCT.PD_OP IS '상품옵션';

COMMENT ON COLUMN TBL_PRODUCT.PD_STOCK IS '상품재고';

COMMENT ON COLUMN TBL_PRODUCT.CAT_MAIN IS '대분류카테고리';

COMMENT ON COLUMN TBL_PRODUCT.CAT_SUB IS '소분류카테고리';


DROP TABLE TBL_REVIEW;

CREATE TABLE TBL_REVIEW
(
    REVIEW_CODE    NUMBER NOT NULL,
    PD_GRADE    NUMBER NOT NULL,
    REVIEW_CONTENT    VARCHAR2(1000) NOT NULL,
    UPLOAD_DATE    DATE NOT NULL,
    REVIEW_COMMENT    VARCHAR2(500),
    PD_CODE    NUMBER NOT NULL,
    MEMBER_CODE    NUMBER NOT NULL
);

ALTER TABLE TBL_REVIEW
DROP PRIMARY KEY;

ALTER TABLE TBL_REVIEW
 ADD CONSTRAINT TBL_REVIEW_PK PRIMARY KEY ( REVIEW_CODE );
 
DROP SEQUENCE SEQ_REVIEW_CODE;
CREATE SEQUENCE SEQ_REVIEW_CODE
START WITH 1
NOCACHE;

COMMENT ON COLUMN TBL_REVIEW.REVIEW_CODE IS '리뷰코드';

COMMENT ON COLUMN TBL_REVIEW.PD_GRADE IS '평점';

COMMENT ON COLUMN TBL_REVIEW.REVIEW_CONTENT IS '리뷰내용';

COMMENT ON COLUMN TBL_REVIEW.UPLOAD_DATE IS '등록일';

COMMENT ON COLUMN TBL_REVIEW.REVIEW_COMMENT IS '리뷰댓글';

COMMENT ON COLUMN TBL_REVIEW.PD_CODE IS '상품코드';

COMMENT ON COLUMN TBL_REVIEW.MEMBER_CODE IS '회원코드';


DROP TABLE TBL_SHOP;

CREATE TABLE TBL_SHOP
(
    SHOP_NM    VARCHAR2(100) NOT NULL,
    SHOP_WEB_ADS    VARCHAR2(255),
    SHOP_EMAIL    VARCHAR2(40) NOT NULL,
    SHOP_DESC    VARCHAR2(1000),
    OM_ST    VARCHAR2(10) NOT NULL,
    OM_NUM    VARCHAR2(100) NOT NULL,
    CS_TEL    VARCHAR2(100) NOT NULL,
    CS_EMAIL    VARCHAR2(100) NOT NULL,
    CS_HOUR    VARCHAR2(100) NOT NULL,
    PIC_NM    VARCHAR2(100) NOT NULL,
    PIC_TEL    VARCHAR2(100) NOT NULL,
    PIC_EMAIL    VARCHAR2(100) NOT NULL
);

ALTER TABLE TBL_SHOP
DROP PRIMARY KEY;

ALTER TABLE TBL_SHOP
 ADD CONSTRAINT TBL_SHOP_PK PRIMARY KEY ( SHOP_NM );

COMMENT ON COLUMN TBL_SHOP.SHOP_NM IS '쇼핑몰명';

COMMENT ON COLUMN TBL_SHOP.SHOP_WEB_ADS IS '쇼핑몰 주소';

COMMENT ON COLUMN TBL_SHOP.SHOP_EMAIL IS '쇼핑몰 이메일';

COMMENT ON COLUMN TBL_SHOP.SHOP_DESC IS '쇼핑몰 소개';

COMMENT ON COLUMN TBL_SHOP.OM_ST IS '통신판매업 신고여부';

COMMENT ON COLUMN TBL_SHOP.OM_NUM IS '통신판매신고 번호';

COMMENT ON COLUMN TBL_SHOP.CS_TEL IS '고객센터 번호';

COMMENT ON COLUMN TBL_SHOP.CS_EMAIL IS '고객센터 이메일';

COMMENT ON COLUMN TBL_SHOP.CS_HOUR IS '고객센터 운영시간';

COMMENT ON COLUMN TBL_SHOP.PIC_NM IS '개인정보보호 책임자';

COMMENT ON COLUMN TBL_SHOP.PIC_TEL IS '개인정보보호 책임자 연락처';

COMMENT ON COLUMN TBL_SHOP.PIC_EMAIL IS '개인정보보호 책임자 이메일';


